#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid holding its PID
# Displays To infinity and beyond indefinitely
# Displays I despise the kill command.

# of Displays Y U no love me? when a SIGINT signal is received

# Upon receiving a SIGQUIT or SIGTERM signal, deletes the file /var/run/myscript.pid and ends the script.

terminator()
{
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT
done
