#!/usr/bin/env bash
# a Bash script that displays the PID, along with the process name,
# processes whose name contain the word bash.

# Requirements:
# You cannot use ps

while true
do
echo "To infinity and beyond"
sleep 2
done
