#!/usr/bin/env bash
# a Bash script that displays To infinity and beyond indefinitely.

# Requirements:
# In between each iteration of the loop, add a sleep 2

kill "$(pgrep -f 4-to_infinity_and_beyond)"
