#!/usr/bin/env bash
# This script code is for displaying "Best School" 10 times
# but prints Hi at 9 using while loop and if statement
i=0
while ((i < 10))
do
	echo "Best School"
	((i++))
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
done
