#!/usr/bin/env bash
# This script code is for displaying "Best School" 10 times
# but prints Hi at 9
# using while loop and if, elif and else statements
i=0
while ((i < 10))
do
	((i++))
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
