#!/usr/bin/env bash
# This script code is for displaying "Best School" 10 times
# but prints Hi at 9
# using while loop and case statement
i=1
while ((i < 21))
do
	echo $i
	case "$i" in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
		esac
	((i++))
done
