#!/usr/bin/env bash
# Write a Bash script that configures an Ubuntu server with the below requirements.

# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
# The checker is running on Docker, so make sure to read this

# For checking if the script is running inside Docker or not
if [ -f "/.dockerenv" ]; then
	# For modifing the /etc/hosts to change the IP addresses
	sudo sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts
	sudo sed -i 's/157.240.11.35 facebook.com/8.8.8.8 facebook.com/' /etc/hosts
	
	echo "Hosts file updated successfully."
else
	echo "This script is intended to run inside a Docker container."
	echo "Exiting..."
fi
