#!/usr/bin/env bash
# Write a Bash script that displays all active IPv4 IPs on the machine it’s executed on.

# For getting the hostname of the machine
hostname=$(hostname)

# For getting the list of IP addresses associated with the hostname
ipv4_addresses=$(getent hosts "$hostname" | awk '{print $1}')

# For printing each IPv4 address
for ip in $ipv4_addresses; do
	echo "$ip"
done
